package ru.mdc.displaycontroller;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothSocket;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.media.AudioManager;
import android.os.Build;
import android.os.Bundle;
import android.os.Environment;
import android.os.SystemClock;
import android.provider.Settings;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int REQ_BT = 31;
    private static final UUID SPP_UUID = UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
    private static final long GESTURE_MS = 420L;
    private static final String[] DISCOVERY_KEYS = {"can","canbus","mcu","vehicle","carservice","carinfo","steer","raise","rzc","mazda","ts10","topway","fyt","syu","radio"};
    private final ExecutorService io = Executors.newSingleThreadExecutor();
    private final List<String> events = new ArrayList<>();
    private final Telemetry telemetry = new Telemetry();
    private BluetoothSocket socket; private InputStream in; private OutputStream out; private volatile boolean polling;
    private String obdStage="IDLE", transport="NONE", elmIdentity="UNKNOWN", ecuState="NOT_REACHED", supportedPids="UNKNOWN", lastError="", discoverySummary="NOT RUN";
    private long lastUpMs=-1,lastDownMs=-1; private Runnable pendingUp,pendingDown; private boolean replaying;
    private long tripLastMs; private double tripKm,tripFuelL;
    private LinearLayout content; private TextView status;

    @Override public void onCreate(Bundle b){super.onCreate(b);buildShell();log("APP_START safety="+BuildConfig.SAFETY_PROFILE+" CAN_WRITE="+BuildConfig.CAN_WRITE);showDashboard();ensureBluetoothPermission();}
    private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,-1,1);}
    private TextView text(String s,int sp,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setPadding(18,10,18,10);return t;}
    private Button action(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);b.setMinHeight(62);return b;}
    private Button nav(String s,View.OnClickListener l){Button b=action(s,l);b.setTextSize(14);return b;}
    private void buildShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(8,10,13));status=text("MDC 1.0.1 internal-1 • OBD IDLE • CAN WRITE OFF",16,Color.LTGRAY);root.addView(status);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout n=new LinearLayout(this);n.addView(nav("OEM",v->showOem()),weight());n.addView(nav("RETRO",v->showRetro()),weight());n.addView(nav("DASHBOARD",v->showDashboard()),weight());n.addView(nav("DIAGNOSTICS",v->showDiagnostics()),weight());n.addView(nav("SETTINGS",v->showSettings()),weight());root.addView(n,new LinearLayout.LayoutParams(-1,72));setContentView(root);}
    private void clear(String title){content.removeAllViews();TextView h=text(title,30,Color.WHITE);h.setGravity(Gravity.CENTER_HORIZONTAL);content.addView(h);}
    private void showOem(){clear("OEM COMPUTER");content.addView(text("OEM BRIDGE: LOCKED • CAN WRITE: OFF",18,Color.rgb(255,120,80)));content.addView(text("Непроверенные команды в автомобиль не отправляются.",15,Color.LTGRAY));content.addView(action("INFO",v->blocked("INFO_NEXT")));content.addView(action("CLOCK",v->{log("CLOCK_LOCAL_SETTINGS");try{startActivity(new android.content.Intent(Settings.ACTION_DATE_SETTINGS));}catch(Exception e){toast("Android clock settings unavailable");}}));content.addView(action("RESET MDC TRIP",v->new AlertDialog.Builder(this).setTitle("Сбросить MDC Trip?").setMessage("Только локальный TripComputer; OEM/CAN команда не отправляется.").setPositiveButton("RESET",(d,w)->{tripKm=0;tripFuelL=0;tripLastMs=0;log("MDC_TRIP_RESET");showOem();}).setNegativeButton("Отмена",null).show()));content.addView(action("SET",v->blocked("SET")));content.addView(action("TIME +",v->blocked("TIME_PLUS")));content.addView(action("TIME −",v->blocked("TIME_MINUS")));}
    private void showRetro(){clear("RETRO");content.addView(text("OEM-inspired local control surface",16,Color.LTGRAY));LinearLayout r=new LinearLayout(this);r.addView(action("INFO",v->blocked("INFO_NEXT")),weight());r.addView(action("CLOCK",v->showOem()),weight());r.addView(action("RESET",v->{tripKm=0;tripFuelL=0;log("MDC_TRIP_RESET_RETRO");}),weight());r.addView(action("SET",v->blocked("SET")),weight());content.addView(r);LinearLayout m=new LinearLayout(this);m.addView(action("◀ PREV",v->replayMedia(KeyEvent.KEYCODE_MEDIA_PREVIOUS)),weight());m.addView(action("NEXT ▶",v->replayMedia(KeyEvent.KEYCODE_MEDIA_NEXT)),weight());content.addView(m);content.addView(text("INFO/SET/OEM clock write locked. Media buttons use Android media control only.",15,Color.LTGRAY));}
    private void showDashboard(){clear("DASHBOARD");content.addView(text(metric("SPEED",telemetry.speed,"km/h")+"     "+metric("RPM",telemetry.rpm,"rpm"),24,Color.WHITE));content.addView(text(metric("COOLANT",telemetry.coolant,"°C")+"     "+metric("VOLT",telemetry.voltage,"V"),22,Color.WHITE));content.addView(text(metric("MAF",telemetry.maf,"g/s")+"     "+metric("FUEL",telemetry.fuelPct,"%"),20,Color.WHITE));content.addView(text(String.format(Locale.US,"TRIP %.2f km     FUEL %.3f L     AVG %s",tripKm,tripFuelL,tripKm>.2?String.format(Locale.US,"%.1f L/100",tripFuelL/tripKm*100):"--"),20,Color.WHITE));content.addView(text("Source: OBD_DIRECT / CALC_MAF. Missing data is never replaced by zero.",14,Color.LTGRAY));content.addView(action("CONNECT / SELECT ELM",v->chooseBondedDevice()));content.addView(action("REFRESH",v->showDashboard()));}
    private String metric(String n,Double v,String unit){return n+" "+(v==null?"--":String.format(Locale.US,v%1==0?"%.0f":"%.1f",v))+" "+unit;}
    private void showDiagnostics(){clear("DIAGNOSTICS");content.addView(text("OBD: "+obdStage+"\nTransport: "+transport+"\nELM: "+elmIdentity+"\nECU: "+ecuState+"\nPIDs: "+supportedPids+"\nLast error: "+lastError,17,Color.WHITE));content.addView(text("Steering: physical UP=88 / DOWN=87\nDouble window=420 ms\nCAN_WRITE=false",16,Color.LTGRAY));content.addView(text("TS10/RZ-MZD05 discovery:\n"+discoverySummary,15,Color.LTGRAY));content.addView(action("RUN READ-ONLY TS10 DISCOVERY",v->runDiscovery()));content.addView(action("COPY SUPPORT REPORT",v->copyReport()));content.addView(action("SAVE SUPPORT REPORT",v->saveReport()));content.addView(action("CONNECT / SELECT ELM",v->chooseBondedDevice()));}
    private void showSettings(){clear("SETTINGS");content.addView(text("Vehicle: Mazda 3 BK 1.6 facelift\nHead unit: TS10S / UIS7862A\nCAN box: RZ-MZD05\nSafety: "+BuildConfig.SAFETY_PROFILE,18,Color.WHITE));content.addView(text("OBD tries secure SPP first, then insecure RFCOMM SPP. Insecure RFCOMM changes Bluetooth socket authentication only; it does not send different ECU commands.",15,Color.LTGRAY));content.addView(action("CONNECT / SELECT ELM",v->chooseBondedDevice()));content.addView(action("RUN DISCOVERY",v->runDiscovery()));}
    private void blocked(String c){log("OEM_COMMAND_BLOCKED "+c);toast(c+": LOCKED_UNVALIDATED_PROTOCOL");}
    private void ensureBluetoothPermission(){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT},REQ_BT);}
    private void chooseBondedDevice(){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){ensureBluetoothPermission();return;}BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a==null){fail("BT_ADAPTER_UNAVAILABLE");return;}if(!a.isEnabled()){fail("BT_DISABLED");return;}Set<BluetoothDevice> set=a.getBondedDevices();if(set==null||set.isEmpty()){fail("BT_DEVICE_NOT_PAIRED");toast("Нет сопряжённых Bluetooth устройств");return;}List<BluetoothDevice> ds=new ArrayList<>(set);String[] labels=new String[ds.size()];for(int i=0;i<ds.size();i++){BluetoothDevice d=ds.get(i);String addr=d.getAddress();labels[i]=(d.getName()==null?"Unknown":d.getName())+"  ["+(addr.length()>8?addr.substring(0,8):addr)+"…]";}new AlertDialog.Builder(this).setTitle("Выбери ELM/OBD адаптер").setItems(labels,(d,w)->connectObd(ds.get(w))).show();}
    private void connectObd(BluetoothDevice device){polling=false;closeSocket();obdStage="TRANSPORT_CONNECT";ecuState="NOT_REACHED";lastError="";updateStatus();io.submit(()->{try{BluetoothSocket s;try{transport="SPP_SECURE";logBg("OBD_TRANSPORT_ATTEMPT SPP_SECURE");s=device.createRfcommSocketToServiceRecord(SPP_UUID);s.connect();}catch(Exception first){logBg("SPP_SECURE_FAILED "+first.getClass().getSimpleName());transport="SPP_INSECURE";s=device.createInsecureRfcommSocketToServiceRecord(SPP_UUID);s.connect();}socket=s;in=s.getInputStream();out=s.getOutputStream();obdStage="ELM_HANDSHAKE";updateStatusBg();elmHandshake();obdStage="ECU_PROBE";updateStatusBg();String p=elm("0100",4500);if(p.contains("UNABLETOCONNECT")||p.contains("NODATA")){ecuState="UNAVAILABLE";throw new Exception("ECU_UNABLE_TO_CONNECT: "+p);}ecuState="CONNECTED";supportedPids=p;obdStage="STREAMING";updateStatusBg();polling=true;tripLastMs=SystemClock.elapsedRealtime();pollLoop();}catch(Exception e){lastError=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();obdStage="FAILED";logBg("OBD_FAILED "+lastError);updateStatusBg();closeSocket();}});}
    private void elmHandshake() throws Exception{String[] cs={"ATZ","ATE0","ATL0","ATS0","ATH0","ATSP0","ATAT1"};for(String c:cs){String r=elm(c,c.equals("ATZ")?4500:2200);logBg("ELM "+c+" => "+clip(r));if(c.equals("ATZ")&&(r.isEmpty()||r.contains("TIMEOUT")))throw new Exception("ELM_NO_PROMPT");}try{elmIdentity=elm("ATI",1800);}catch(Exception ignored){}}
    private void pollLoop() throws Exception{while(polling&&socket!=null&&socket.isConnected()){long st=SystemClock.elapsedRealtime();telemetry.rpm=parsePid(elm("010C",1800),0x0C);telemetry.speed=parsePid(elm("010D",1800),0x0D);telemetry.coolant=parsePid(elm("0105",1800),0x05);telemetry.maf=parsePid(elm("0110",1800),0x10);telemetry.fuelPct=parsePid(elm("012F",1800),0x2F);Double df=parsePid(elm("015E",1800),0x5E);telemetry.fuelRate=df!=null?df:deriveFuelRate(telemetry.maf);telemetry.voltage=parseVoltage(elm("ATRV",1800));integrateTrip();runOnUiThread(()->{updateStatus();if(isDashboardVisible())showDashboard();});SystemClock.sleep(Math.max(100,1000-(SystemClock.elapsedRealtime()-st)));}}
    private boolean isDashboardVisible(){return content.getChildCount()>0&&content.getChildAt(0) instanceof TextView&&((TextView)content.getChildAt(0)).getText().toString().contains("DASHBOARD");}
    private String elm(String command,long timeout)throws Exception{if(out==null||in==null)throw new Exception("TRANSPORT_NOT_CONNECTED");while(in.available()>0)in.read();out.write((command+"\r").getBytes(StandardCharsets.US_ASCII));out.flush();long dl=SystemClock.elapsedRealtime()+timeout;StringBuilder b=new StringBuilder();while(SystemClock.elapsedRealtime()<dl){while(in.available()>0){int x=in.read();if(x<0)throw new Exception("TRANSPORT_EOF");char c=(char)x;if(c=='>')return normalize(b.toString());b.append(c);}SystemClock.sleep(15);}throw new Exception("ELM_TIMEOUT_"+command);}
    private static String normalize(String s){return s.toUpperCase(Locale.US).replace(" ","").replace("\r","").replace("\n","");} private static String clip(String s){return s.length()>80?s.substring(0,80):s;}
    private Double parsePid(String r,int pid){try{String mark=String.format(Locale.US,"41%02X",pid);int i=r.indexOf(mark);if(i<0)return null;String d=r.substring(i+4);switch(pid){case 0x0C:return Integer.parseInt(d.substring(0,4),16)/4.0;case 0x0D:return (double)Integer.parseInt(d.substring(0,2),16);case 0x05:return Integer.parseInt(d.substring(0,2),16)-40.0;case 0x10:return Integer.parseInt(d.substring(0,4),16)/100.0;case 0x2F:return Integer.parseInt(d.substring(0,2),16)*100.0/255.0;case 0x5E:return Integer.parseInt(d.substring(0,4),16)/20.0;}}catch(Exception ignored){}return null;}
    private Double parseVoltage(String r){try{String x=r.replace("V","");int i=0;while(i<x.length()&&!(Character.isDigit(x.charAt(i))||x.charAt(i)=='.'))i++;int j=i;while(j<x.length()&&(Character.isDigit(x.charAt(j))||x.charAt(j)=='.'))j++;return Double.parseDouble(x.substring(i,j));}catch(Exception e){return null;}}
    private Double deriveFuelRate(Double maf){return maf==null?null:maf*3600.0/(14.7*745.0);} private void integrateTrip(){long now=SystemClock.elapsedRealtime();if(tripLastMs==0){tripLastMs=now;return;}double h=(now-tripLastMs)/3600000.0;tripLastMs=now;if(h<=0||h>5.0/3600.0)return;if(telemetry.speed!=null)tripKm+=telemetry.speed*h;if(telemetry.fuelRate!=null)tripFuelL+=telemetry.fuelRate*h;}
    private void runDiscovery(){discoverySummary="RUNNING";showDiagnostics();io.submit(()->{StringBuilder b=new StringBuilder("MDC_TS10_DISCOVERY_SCHEMA=2\nREAD_ONLY=true\nCAN_WRITE=false\n");collectCommand(b,"getprop");collectCommand(b,"service list");collectCommand(b,"pm list packages");collectFiles(b,new File("/dev"));collectFiles(b,new File("/vendor/lib64"));collectFiles(b,new File("/vendor/lib"));collectFiles(b,new File("/system/lib64"));String s=b.toString();discoverySummary=s.length()>12000?s.substring(0,12000)+"\n[TRUNCATED]":s;logBg("DISCOVERY_COMPLETE chars="+discoverySummary.length());runOnUiThread(this::showDiagnostics);});}
    private void collectCommand(StringBuilder b,String cmd){b.append("\n## ").append(cmd).append('\n');try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",cmd});BufferedReader r=new BufferedReader(new java.io.InputStreamReader(p.getInputStream()));String l;int n=0;while((l=r.readLine())!=null&&n<1500){if(matches(l)){b.append(sanitize(l)).append('\n');n++;}}p.waitFor();}catch(Exception e){b.append("collector_error=").append(e.getClass().getSimpleName()).append('\n');}}
    private void collectFiles(StringBuilder b,File d){b.append("\n## files ").append(d.getPath()).append('\n');try{File[] fs=d.listFiles();if(fs==null)return;int n=0;for(File f:fs)if(n<300&&matches(f.getName())){b.append(f.getPath()).append(" readable=").append(f.canRead()).append('\n');n++;}}catch(Exception e){b.append("collector_error=").append(e.getClass().getSimpleName()).append('\n');}}
    private boolean matches(String s){String x=s.toLowerCase(Locale.US);for(String k:DISCOVERY_KEYS)if(x.contains(k))return true;return false;} private String sanitize(String s){return s.replaceAll("(?i)([0-9a-f]{2}:){5}[0-9a-f]{2}","REDACTED_MAC").replaceAll("\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b","REDACTED_IP").replaceAll("[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}","REDACTED_EMAIL");}
    private String report(){StringBuilder b=new StringBuilder();b.append("MDC_SUPPORT_REPORT_SCHEMA=1\nVERSION=1.0.1-internal-1\nMDC_SAFETY_PROFILE=").append(BuildConfig.SAFETY_PROFILE).append("\nCAN_WRITE=").append(BuildConfig.CAN_WRITE).append("\nREAD_ONLY_DIAGNOSTICS=true\n\n");b.append("[DEVICE]\nmanufacturer=").append(Build.MANUFACTURER).append("\nmodel=").append(Build.MODEL).append("\nandroid=").append(Build.VERSION.RELEASE).append("\nsdk=").append(Build.VERSION.SDK_INT).append('\n');b.append("\n[VEHICLE]\nprofile=Mazda3_BK_1.6_facelift\nheadUnit=TS10S_UIS7862A\ncanBox=RZ-MZD05\n");b.append("\n[OBD]\nstage=").append(obdStage).append("\ntransport=").append(transport).append("\nerror=").append(sanitize(lastError)).append('\n');b.append("\n[ELM]\nidentity=").append(sanitize(elmIdentity)).append('\n');b.append("\n[ECU]\nstate=").append(ecuState).append("\nsupportedPids=").append(supportedPids).append('\n');b.append("\n[STEERING]\nphysicalUpKey=88\nphysicalDownKey=87\ndoubleWindowMs=420\n");b.append("\n[TRIP]\ndistanceKm=").append(String.format(Locale.US,"%.3f",tripKm)).append("\nfuelL=").append(String.format(Locale.US,"%.4f",tripFuelL)).append('\n');b.append("\n[OEM]\nbridge=LOCKED\nINFO=LOCKED\nCLOCK_OEM=LOCKED\nRESET_OEM=LOCKED\n");b.append("\n[DISCOVERY]\n").append(discoverySummary).append('\n');b.append("\n[SAFETY]\nCAN_WRITE=false\nOBD_WRITE=false\nOEM_WRITE=false\nUNKNOWN_BINDER_CALL=false\nUNKNOWN_BROADCAST_SEND=false\nDEVICE_NODE_WRITE=false\n\n[RECENT_EVENTS]\n");synchronized(events){for(String e:events)b.append(e).append('\n');}return sanitize(b.toString());}
    private void copyReport(){ClipboardManager c=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("MDC support report",report()));toast("Support report copied");}
    private void saveReport(){try{File d=getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS);if(d==null)d=getFilesDir();String ts=new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.US).format(new Date());File f=new File(d,"MDC-support-"+ts+".txt");try(java.io.FileOutputStream fos=new java.io.FileOutputStream(f)){fos.write(report().getBytes(StandardCharsets.UTF_8));}toast("Saved: "+f.getAbsolutePath());}catch(Exception e){toast("EXPORT_FAILED: "+e.getMessage());}}
    @Override public boolean dispatchKeyEvent(KeyEvent e){if(replaying)return super.dispatchKeyEvent(e);if(e.getAction()!=KeyEvent.ACTION_UP)return super.dispatchKeyEvent(e);int k=e.getKeyCode();if(k!=KeyEvent.KEYCODE_MEDIA_PREVIOUS&&k!=KeyEvent.KEYCODE_MEDIA_NEXT)return super.dispatchKeyEvent(e);long now=SystemClock.elapsedRealtime();if(k==KeyEvent.KEYCODE_MEDIA_PREVIOUS){if(lastUpMs>=0&&now-lastUpMs<=GESTURE_MS){if(pendingUp!=null)status.removeCallbacks(pendingUp);lastUpMs=-1;pendingUp=null;log("STEERING_DOUBLE_UP");toast("MDC ◀ previous page");return true;}lastUpMs=now;pendingUp=()->{lastUpMs=-1;replayMedia(KeyEvent.KEYCODE_MEDIA_PREVIOUS);log("STEERING_SINGLE_UP_REPLAY");};status.postDelayed(pendingUp,GESTURE_MS);return true;}else{if(lastDownMs>=0&&now-lastDownMs<=GESTURE_MS){if(pendingDown!=null)status.removeCallbacks(pendingDown);lastDownMs=-1;pendingDown=null;log("STEERING_DOUBLE_DOWN");toast("MDC next page ▶");return true;}lastDownMs=now;pendingDown=()->{lastDownMs=-1;replayMedia(KeyEvent.KEYCODE_MEDIA_NEXT);log("STEERING_SINGLE_DOWN_REPLAY");};status.postDelayed(pendingDown,GESTURE_MS);return true;}}
    private void replayMedia(int key){AudioManager am=(AudioManager)getSystemService(AUDIO_SERVICE);replaying=true;try{am.dispatchMediaKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,key));am.dispatchMediaKeyEvent(new KeyEvent(KeyEvent.ACTION_UP,key));}finally{status.postDelayed(()->replaying=false,250);}}
    private void fail(String s){lastError=s;obdStage="FAILED";log(s);updateStatus();} private void updateStatusBg(){runOnUiThread(this::updateStatus);} private void updateStatus(){status.setText("MDC 1.0.1 internal-1 • OBD "+obdStage+" • "+transport+" • CAN WRITE OFF");} private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} private void log(String s){synchronized(events){events.add(stamp()+" "+s);while(events.size()>300)events.remove(0);}} private void logBg(String s){log(s);} private String stamp(){return new SimpleDateFormat("HH:mm:ss.SSS",Locale.US).format(new Date());}
    private void closeSocket(){BluetoothSocket s=socket;socket=null;in=null;out=null;closeQuiet(s);} private void closeQuiet(BluetoothSocket s){try{if(s!=null)s.close();}catch(Exception ignored){}} @Override protected void onDestroy(){polling=false;closeSocket();io.shutdownNow();super.onDestroy();}
    private static final class Telemetry{Double speed,rpm,coolant,maf,fuelPct,fuelRate,voltage;}
}
